### ISSUE TITLE
Click "space" and "Enter" from terminal menu, get unhandled 'error': write after end

### ISSUE THREAD

**Issue by dylanwind** [rvagg/workshopper#108]
The issue is,

open CMD,
type "learnyounode", the terminal menu display.
now click "space", the menu disappear,
then click "enter",
get below error output:
_events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (C:\Users\<myName>\AppData\Roaming\npm\node_modules\learnyounode\node
_modules\workshopper\node_modules\terminal-menu\node_modules\duplexer2\node_modules\readab
le-stream\lib\_stream_writable.js:161:12)
    at DuplexWrapper.Writable.write (C:\Users\<myName>\AppData\Roaming\npm\node_modules\le
arnyounode\node_modules\workshopper\node_modules\terminal-menu\node_modules\duplexer2\node
_modules\readable-stream\lib\_stream_writable.js:208:5)
    at ReadStream.passDataToMenu (C:\Users\<myName>\AppData\Roaming\npm\node_modules\learn
younode\node_modules\workshopper\menu.js:69:16)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at TTY.onread (net.js:538:20)_

**Comment by dylanwind** [comment]
Here is the discussion and 2 guys confirm it's an issue.
https://github.com/nodeschool/discussions/issues/1084#issuecomment-94143581

**Comment by TimothyGu** [comment]
I can confirm this as well. Typing "q" instead of "space" results in the same error.
